mm: Remove PRLMK unused variables on process reclaim
* Fixes this compilation error:

../../../../../../kernel/xiaomi/sdm660/mm/process_reclaim.c:217:6: error: unused variable 'i' [-Werror,-Wunused-variable]
        int i, j, max = si;
            ^
../../../../../../kernel/xiaomi/sdm660/mm/process_reclaim.c:217:9: error: unused variable 'j' [-Werror,-Wunused-variable]
        int i, j, max = si;

* Thanks @psndna88